spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/heroes?serverTimezone=America/Bogota
    username: root
    password: Admin0000
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

  messages:
    basename: bundles/apiLanguageBundle

logging:
  level:
    root: INFO
  file: heroapi.log

